version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testsecret
      POSTGRES_DB: inkwave
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  # backend:
  #   image: your-backend-image:latest
  #   depends_on:
  #     - db
  #     - redis
  #     - ai_service
  #   networks:
  #     - backend
  #     - ai_network
  #
  # frontend:
  #   image: your-frontend-image:latest
  #   depends_on:
  #     - backend
  #   networks:
  #     - frontend
  #
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - frontend
  #
  # ai_service:
  #   image: your-ai-service-image:latest
  #   networks:
  #     - ai_network

volumes:
  db_data:

networks:
  backend:
  frontend:
  ai_network:
